# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgblog',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='imgblog',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='imgblog',
            name='context',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='imgblog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='imgblog',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
